# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODkyZmFhZDE2YjhjMTk5NGMzZDMyNmFiYTliZWFkMDYwMDRmYjkzZThlMjg3NTljNDk1Y2E3M2RkMGM2YWNiMGNjYTliYmI1YjQzNWVjYzQyMGFlNzU0MTQ4ZTVlNmI1MWNlNWYwZjBkYjMwMzlkZTMwNTU3MWNlYWMyNzgzMGU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
